theme: jekyll-theme-minimal
title: idkaaa's CS6750 Spring 2022 homepage
description: Publicly shared notes and information for Dr. Joyner's Spring 2022 CS6750 - Human Computer Interaction (HCI) course